### Testes

### Get Dataframe data
GET http://localhost:5000/getDataframe?ano=2023&mes=dezembro
Authorization: JWT

### Download excel dataframe data
GET http://localhost:5000/getDataframe/download?ano=2023&mes=dezembro
Authorization: JWT

### Login JWT create
GET http://localhost:5000/login
?username=Lucas-Ribeiro-Lima
&password=123456

### Test JWT
GET http://localhost:5000/getUser
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJMdWNhcy1SaWJlaXJvLUxpbWEiLCJleHAiOjE3MDczMTM4MzIsImF2YXRhcl91cmwiOiJodHRwczovL2dpdGh1Yi5jb20vTHVjYXMtUmliZWlyby1MaW1hLnBuZyJ9.fuH6QIU2pa2H4rexTOGSko_cHa-KQ57VZrcay4K1TDM