### Testes

### Get Dataframe data
GET http://localhost:5000/getDataframe?ano=2023&mes=dezembro
Authorization: JWT

### Download excel dataframe data
GET http://localhost:5000/getDataframe/download?ano=2023&mes=dezembro
Authorization: JWT

### Login JWT create
GET http://localhost:5000/login
?username=Lucas-Ribeiro-Lima
&password=12345

### Test JWT
GET http://localhost:5000/getUser
Authorization: JWT